name: Update KEGG Data

on:
  schedule:
    # Run at 00:00 on Sunday (UTC)
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.branches }}
    steps:
      - name: Get branches
        id: set-branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Get branches matching 'devel' or 'RELEASE_*'
          # Using gh cli to fetch branches
          branches=$(gh api repos/$REPO/branches --paginate --jq '[.[] | select(.name == "devel" or (.name | test("^RELEASE_"))) | .name]')
          echo "branches=$branches" >> $GITHUB_OUTPUT

  update-data:
    needs: get-branches
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.branches) }}
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rvest
            any::tibble
            any::tidyr
            any::devtools
            local::.
          needs: check

      - name: Install package
        run: |
          Rscript -e 'devtools::install()'

      - name: Update KEGG Data
        run: |
          Rscript -e 'source(system.file("extdata/kegg_pathway_category.r", package="clusterProfiler"))'
          Rscript -e 'clusterProfiler:::get_kegg_species(save=TRUE)'
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update KEGG data"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-kegg-data-${{ matrix.branch }}
          base: ${{ matrix.branch }}
          delete-branch: true
          title: 'chore: Update KEGG internal data'
          body: |
            This PR updates the internal KEGG data (`kegg_category.rda` and `kegg_species.rda`) for branch `${{ matrix.branch }}`.
            
            - Auto-generated by GitHub Actions.
          labels: |
            automated pr
            data update
